### ISSUE TITLE
hi~ i have not found the datasets directory

### ISSUE THREAD

**Issue by miss1997yuan** [dmarcosg/SIAM#1]
hello, i am very interested in your work,while i run the train_siam.py, i have not found the datasets directory as the figure,would you give me some suggestion ?
![image](https://user-images.githubusercontent.com/30165188/67956342-e4de9b80-fc2e-11e9-920f-75b8a5b48ef1.png)

**Comment by dmarcosg** [comment]
Hello! Thanks for your interest! I will make the code self-contained and
document it in the following weeks.
I'll let you know as soon as it's ready.

**Comment by dmarcosg** [comment]
I added the missing functions :)
